---
title: "An overview of making rangeModelMetadata objects"
author: "Cory Merow, Brian Maitner, Hannah Owens"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    fig_caption: yes
    toc: true
    toc_depth: 3
vignette: >
  %\VignetteIndexEntry{An overview of making rangeModelMetadata objects}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rangeModelMetadata)
```

A simple `rmm` object is a list.
```{r}
rmm1=rangeModelMetadataTemplate(useCase='apObligate')
str(rmm1)
```

A more complex `rmm` object with all predefined fields.
```{r}
rmm2=rangeModelMetadataTemplate(useCase='apAll')
str(rmm2)
```

Not sure what to enter in different fields? We can suggest options.

```{r}
rmmSuggest('dataPrep',fullFieldDepth=FALSE)
rmmSuggest('dataPrep',fullFieldDepth=TRUE) # for all fields below the specified one
rmmSuggest('dataPrep$errors$duplicateRemoval')
rmmSuggest('dataPrep$errors$duplicateRemoval$rule')
```

Another more complex example

```{r}
rmmSuggest('model')
rmmSuggest('model$algorithmSettings$')
rmmSuggest('model$algorithmSettings$maxent$')
rmmSuggest('$model$algorithmSettings$maxent$featureSet')
```


To make `rmm` objects portable to other interfaces, they are readily written to csv format.
```{r}

```

